Repository krymtkts/pocof, pull requests merged in 2024-12, with the labels that each got.

#265 Replace basic tests with property-based tests.
  src/pocof.Test/Data.fs
Labels: maintenance

#267 Refine the Markdown command help and regenerate the MAML command help.
  docs/pocof/Select-Pocof.md
  src/pocof/pocof-Help.xml
Labels: documentation

#263 Bump .NET to 9 and adjust project settings
  .config/dotnet-tools.json
  global.json
  psakefile.ps1
  src/pocof.Test/Library.fs
  src/pocof.Test/Pocof.fs
  src/pocof.Test/Query.fs
  src/pocof.Test/Screen.fs
  src/pocof.Test/pocof.Test.fsproj
  src/pocof/Data.fs
  src/pocof/Keys.fs
  src/pocof/Library.fs
  src/pocof/pocof.fsproj
Labels: enhancement

#268 Enhance usability of Select-Pocof command parameters.
  docs/pocof/Select-Pocof.md
  src/pocof/Library.fs
  src/pocof/pocof-Help.xml
  tests/pocof.Tests.ps1
Labels: maintenance

#269 Update the Markdown command help to remove unnecessary sentences.
  docs/pocof/Select-Pocof.md
Labels: documentation

#270 Fix document link
  README.md
Labels: documentation

#272 Update GitHub Actions workflow for Snyk and test execution
  .github/workflows/pr.yml
Labels: maintenance

#274 Fix a typo.
  README.md
Labels: documentation

#276 Refactor query result to use lazy evaluation.
  src/pocof.Test/Data.fs
  src/pocof.Test/Handle.fs
  src/pocof.Test/Pocof.fs
  src/pocof.Test/Query.fs
  src/pocof.Test/Screen.fs
  src/pocof/Data.fs
  src/pocof/Library.fs
  src/pocof/Pocof.fs
  src/pocof/Query.fs
  src/pocof/Screen.fs
Labels: enhancement

#278 Refine test project file.
  src/pocof.Test/pocof.Test.fsproj
Labels: maintenance

#279 Bump version to 0.18.0.
  docs/pocof/Select-Pocof.md
  src/pocof/pocof-Help.xml
  src/pocof/pocof.fsproj
  src/pocof/pocof.psd1
Labels: enhancement

#281 Adjust query window width calculation
  src/pocof.Test/Data.fs
  src/pocof/Data.fs
Labels: bug

#282 Bump version to 0.18.1.
  src/pocof/pocof.fsproj
  src/pocof/pocof.psd1
Labels: enhancement

#284 Make the artifact smarter
  src/pocof/pocof.fsproj
Labels: enhancement

#285 Simplify console width calculation.
  src/pocof.Test/Handle.fs
  src/pocof.Test/Screen.fs
  src/pocof/Data.fs
  src/pocof/Handle.fs
Labels: maintenance

#286 Bump `FsUnit` to 7.0.1 and clean up test project
  src/pocof.Test/Program.fs
  src/pocof.Test/pocof.Test.fsproj
Labels: dependencies, maintenance

#289 Add notes about xUnit compatibility for FsCheck.Xunit and FsUnit.xUnit.
  src/pocof.Test/Program.fs
  src/pocof.Test/pocof.Test.fsproj
Labels: bug, dependencies

#291 Bump `coverlet.collector` to 6.0.3.
  src/pocof.Test/pocof.Test.fsproj
Labels: dependencies
